version: '2.1'
services:
  pickaxe:
    environment:
      LOGDNA_API_KEY: ec8c271f01f545ecf204dd4ba98765ce
      SERVICE__SHARED_SECRET: 5e27500b-2838-4fb3-b2e8-2587101829c8
  sapphire:
    environment:
      service__shared_secret: 5e27500b-2838-4fb3-b2e8-2587101829c8
      rabbitmq__url: amqp://guest:guest@mq:5672/
      db__host: db
      db__port: 5432
      diamond__public_key: |-
          -----BEGIN PUBLIC KEY-----
          MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqyMv2GuBP/41rx4Gich3
          qTnKuBd2XdnifiSpBvrS0uiRsM4O4G/W4NghA1ymQi3/cXJ0qVipZ4eCy1vIl7R6
          Pyl+YqBrzB4iOzgZ0qNJpabGcIZBgBe7hwIKd+0EXdxsGmtx/0YAvTnt5LXtBw4w
          woXqsjeuwgqztMN36sQWb6Qpq0Ee5T0nV3jD8H6Ol9T4egRrh/u781tnouuD1fZy
          pLvVVZtn0GULy10wKeN83THwNc/Z/p0jUnJvQ17t1Hp/4TmqVYeLoQdjG/WqSxs7
          hS+p5dsPcwsCbbAzEYKgAdYWNFgaF0wGBduQ0sNgg6dwlYtFN4MKR9xVsmMrhQCs
          w3nJl7c+otU6YCQy+1iqwDqvN3vdFsFNePP1Xkbza4sS4rg8QT6FKJ94lXFyyl9I
          rsGZZnNNqPPdctJJP5+/lEYIP1ZrNJV96GVmyhklI+yLoC0XeibrQOoxCm+DiXyX
          VBNrFiZznvUin9mjqf1p/TYsMAuhBbJt0NpaT/Iutg5D376YfahXVF4UrA3hdW9Y
          6Jn4MIS8qwD89yDtZn1UUwx6kFSDp/ESahBWHKXyNVNDZtAZMl2bF1CbdJ2lTw88
          NsRLAmjxH6dRoTGlNhdXOlU3XYtt7W9pnx6YIboXa+FT7hYlxps29pK4Mahlfg5J
          DoDzjDSrn8hmjVscLHQ9Tm8CAwEAAQ==
          -----END PUBLIC KEY-----
  emerald:
    environment:
      NODE_ENV: local
      service__shared_secret: 5e27500b-2838-4fb3-b2e8-2587101829c8
      rabbitmq__url: amqp://guest:guest@mq:5672/
      cache__host: cache
      pool__port: 12345
      pool__poolAddress: 9wviCeWe2D8XS82k2ovp5EUYLzBt9pYNW2LXUFsZiv8S3Mt21FZ5qQaAroko1enzw3eGr9qC7X1D7Geoo2RrAotYPwq9Gm8
      monero__daemon__host: 9b7bc232.ngrok.io
      monero__daemon__port: 80
      pickaxe__host: pickaxe
      pickaxe__port: 8050
      diamond__host: diamond
      diamond__port: 8180
      pool__desc: "High end hardware"
      diamond__public_key: |-
          -----BEGIN PUBLIC KEY-----
          MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqyMv2GuBP/41rx4Gich3
          qTnKuBd2XdnifiSpBvrS0uiRsM4O4G/W4NghA1ymQi3/cXJ0qVipZ4eCy1vIl7R6
          Pyl+YqBrzB4iOzgZ0qNJpabGcIZBgBe7hwIKd+0EXdxsGmtx/0YAvTnt5LXtBw4w
          woXqsjeuwgqztMN36sQWb6Qpq0Ee5T0nV3jD8H6Ol9T4egRrh/u781tnouuD1fZy
          pLvVVZtn0GULy10wKeN83THwNc/Z/p0jUnJvQ17t1Hp/4TmqVYeLoQdjG/WqSxs7
          hS+p5dsPcwsCbbAzEYKgAdYWNFgaF0wGBduQ0sNgg6dwlYtFN4MKR9xVsmMrhQCs
          w3nJl7c+otU6YCQy+1iqwDqvN3vdFsFNePP1Xkbza4sS4rg8QT6FKJ94lXFyyl9I
          rsGZZnNNqPPdctJJP5+/lEYIP1ZrNJV96GVmyhklI+yLoC0XeibrQOoxCm+DiXyX
          VBNrFiZznvUin9mjqf1p/TYsMAuhBbJt0NpaT/Iutg5D376YfahXVF4UrA3hdW9Y
          6Jn4MIS8qwD89yDtZn1UUwx6kFSDp/ESahBWHKXyNVNDZtAZMl2bF1CbdJ2lTw88
          NsRLAmjxH6dRoTGlNhdXOlU3XYtt7W9pnx6YIboXa+FT7hYlxps29pK4Mahlfg5J
          DoDzjDSrn8hmjVscLHQ9Tm8CAwEAAQ==
          -----END PUBLIC KEY-----       
  diamond:
    environment:
      NODE_ENV: local
      service__shared_secret: 5e27500b-2838-4fb3-b2e8-2587101829c8
      db__host: db
      db__port: 5432
      mail__sendgrid_key: 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
      jwt__public_key: |-
          -----BEGIN PUBLIC KEY-----
          MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAqyMv2GuBP/41rx4Gich3
          qTnKuBd2XdnifiSpBvrS0uiRsM4O4G/W4NghA1ymQi3/cXJ0qVipZ4eCy1vIl7R6
          Pyl+YqBrzB4iOzgZ0qNJpabGcIZBgBe7hwIKd+0EXdxsGmtx/0YAvTnt5LXtBw4w
          woXqsjeuwgqztMN36sQWb6Qpq0Ee5T0nV3jD8H6Ol9T4egRrh/u781tnouuD1fZy
          pLvVVZtn0GULy10wKeN83THwNc/Z/p0jUnJvQ17t1Hp/4TmqVYeLoQdjG/WqSxs7
          hS+p5dsPcwsCbbAzEYKgAdYWNFgaF0wGBduQ0sNgg6dwlYtFN4MKR9xVsmMrhQCs
          w3nJl7c+otU6YCQy+1iqwDqvN3vdFsFNePP1Xkbza4sS4rg8QT6FKJ94lXFyyl9I
          rsGZZnNNqPPdctJJP5+/lEYIP1ZrNJV96GVmyhklI+yLoC0XeibrQOoxCm+DiXyX
          VBNrFiZznvUin9mjqf1p/TYsMAuhBbJt0NpaT/Iutg5D376YfahXVF4UrA3hdW9Y
          6Jn4MIS8qwD89yDtZn1UUwx6kFSDp/ESahBWHKXyNVNDZtAZMl2bF1CbdJ2lTw88
          NsRLAmjxH6dRoTGlNhdXOlU3XYtt7W9pnx6YIboXa+FT7hYlxps29pK4Mahlfg5J
          DoDzjDSrn8hmjVscLHQ9Tm8CAwEAAQ==
          -----END PUBLIC KEY-----
      jwt__private_key: |-
          -----BEGIN RSA PRIVATE KEY-----
          MIIJKAIBAAKCAgEAqyMv2GuBP/41rx4Gich3qTnKuBd2XdnifiSpBvrS0uiRsM4O
          4G/W4NghA1ymQi3/cXJ0qVipZ4eCy1vIl7R6Pyl+YqBrzB4iOzgZ0qNJpabGcIZB
          gBe7hwIKd+0EXdxsGmtx/0YAvTnt5LXtBw4wwoXqsjeuwgqztMN36sQWb6Qpq0Ee
          5T0nV3jD8H6Ol9T4egRrh/u781tnouuD1fZypLvVVZtn0GULy10wKeN83THwNc/Z
          /p0jUnJvQ17t1Hp/4TmqVYeLoQdjG/WqSxs7hS+p5dsPcwsCbbAzEYKgAdYWNFga
          F0wGBduQ0sNgg6dwlYtFN4MKR9xVsmMrhQCsw3nJl7c+otU6YCQy+1iqwDqvN3vd
          FsFNePP1Xkbza4sS4rg8QT6FKJ94lXFyyl9IrsGZZnNNqPPdctJJP5+/lEYIP1Zr
          NJV96GVmyhklI+yLoC0XeibrQOoxCm+DiXyXVBNrFiZznvUin9mjqf1p/TYsMAuh
          BbJt0NpaT/Iutg5D376YfahXVF4UrA3hdW9Y6Jn4MIS8qwD89yDtZn1UUwx6kFSD
          p/ESahBWHKXyNVNDZtAZMl2bF1CbdJ2lTw88NsRLAmjxH6dRoTGlNhdXOlU3XYtt
          7W9pnx6YIboXa+FT7hYlxps29pK4Mahlfg5JDoDzjDSrn8hmjVscLHQ9Tm8CAwEA
          AQKCAgBeV2doxtrZjCnL/6FbE0fj4hf+o/B8jEBviYYkcuEFo2+tJ+rLjtvF119b
          mxeMJA9NWus078tzZyCTOmW6O6OobhdeB1FllLcKLkMN+zX+O5HpNhmlo2+dXWKn
          +eEOXRS6+8A8GTsPFYAvNJsV6Jy4n1piJJASKBQo8hiJMs+re7P81ElT1gJ6Ffjt
          +tZgnObdXNJqhDt4TEs1ZN+oc9N/PIy+RI1WNF3sHdMPRHjw9zaUc6CY28c9DBiJ
          6yrwlxcn8cIUpEQ04P2hzCu0e660HTJro/dAVDFihl+gp4HNgVd8Q5UegqpPUFrl
          1Q6/hO5rgfsGPxbLxor3a/Pxvg1+TYk5k8lTn73ighfT0EneTDYa8lmwolHSULo6
          CXS4N7BccLdxWXrUK4tSq1DET48Jb63q7Y1L1N4lelFFiQgE32YTYvUBJGfFlF1c
          EQKkDOuIb8uPPo5wrAPABMstTiHhByrvrQEUeFQDZYcFwOA9JyHzpGuw4JAzrDGE
          /p4HU3TYS6cfQNFpW6v2hys29vUU+IfwCQ/OlsxoLRc5L3P90gIclxrI1TphRKO0
          nTZ/KGepwVPOvSduHQ4xUxMom0m9MXz5bRznS6JttDsqNDC4X/efjBQqCn0feta5
          hNJOd8cEJWAjgJ86FYPi5IZkQuVuWojbGZliuzuH38UHesX2AQKCAQEA4mF1GYTG
          u6/XFTluhmFYePFQexfZFxSWmcOrxSiqfcMcS84g1b6cbiZxYo9kj3zdpM7uXaEa
          UrZqtPr4edjHdgZeoC5eIbkgqta1AHiyTMDxXvqg0qZiBhIAXYFrLEQrK1eawa0F
          Ljgb9BdzhV2i/OA++s59upNATZdI3oRftJAscFV4iUe7o2efHhEX2sDzzBSLt3hl
          sKIUMlQCCzGqoA3uW+0XSGObmQ5oDm0WeJe+/D3npEQ5fOBbw9Tl5XiS3xgvGYXG
          MeAPm6dw2BhV0Dfe/8peKq/E4SRIE4zBAuuTjImgtHDp/f902NWwkL3attwmTVAw
          UwtOiWoTEhE5dwKCAQEAwYdgUCg781K9NgQNVK8cxefM3e589M4qcMe6pNVmQ6ux
          VAbw5hTn+yGhEDlzpB+JeAFhcRvwHcs9AB7jazDZOy6kGxTmmR6Ajo14w6baRalt
          FLd/sQaiKVyhQGmdVz8ZMl13mJUorQGsh9OPEmwN+9qaoQopGaG74m+wWB9MP+Ex
          mgANOmEnfRNpiqvfRAMfykh8i/bIGfh8CK37aeEIhdIc6tFLKQAM1DZLJZz0dbf/
          hA7gfC/JKT3UXRH40eHZ5T1nwnMkHLc6WoUmo/VWOrzVXT4Lw22YFhFL9rol7BZM
          nja6arjvaPkwKqYwSYyq1UOwCItONPjQbO10w85QyQKCAQBwjZPzBBjq6Bo/6zYQ
          igW62//vs4Oz/gCCos6cUAO0U3WWGv4oR4TvHx3wquqMjMCGWHwbASZdSWT0ZnNz
          4VwKSlBxw5v5mFmtluKXQWskzikz19ht41uJORoFY3stnxb3ja7b7HJO8Ia1bZN6
          E3wdzkCB4niQcvXdngIU4CvVUnlFwLkVSBz6uWJbSJRbpuOP7AcrSSkGEQ+JlksN
          1bvHqCWCfva8fwm1p3wE8Cfj/U5vizfIbENI2yPE0e0bkj8zvIpuXhyUX5pjAXUR
          e8fuplixRKRdBNcWOTu8vJaaJRZPIX5NOHaeWox14ojO7hX4JKzGc8ATCeQaXirt
          KLMxAoIBAQCjKdXj/uf8j+eCoQv0N+dUW8h33FhxtVhG2b3ctyaPKzRImcmE0l97
          dbDrkuSSnRwzl0ZmLJ3XIMD/Vwt6FicwJHSreIWq1vKgPVpx6jzguqWC7+qyf9s8
          cCJrwh+rrUE7G153wFoY8u5ZXd6kM4Hes0HnQD/Con9bu7q7sTeCLAS7yAtfCwZW
          B4XWKm4EU3X7//0xrBCtBLjeQIFVlSqwWKOUvnxVxvsJ9/SHc7sPfN/qoPhW+5ro
          MH7ZMQvNOFOTWKAgax8pLrn+E4Cuf2wB/a8N+//C9qVhBZg8HllWoL5cLdwhmmYO
          5PjdHFxdxkFJqNXDfl+jfZuMGu91Hn8xAoIBAHszWT+uT5To1hYawJVxqXjJJfpu
          j4z9KG0U3Zv5hEu0ANr9esak7XTgkWVsZkOxxf3DRpR32UPURLZjUIEvYFzM+Zmx
          I0S3855KU52VIOeN8Nbff84z0jfUP82CSle2bGrcyfDwN/zWBG6pjawyvLu0BNx0
          HXIqUvTMaN9xZinXMeZbq6c5XkIyxJSpgzZwm98cY8swCbLD0x7WHvkahGcFF7eL
          FViLNI25tGJr4i7wIOZZGgWJyt/OkeGn92DvfrpWNTyrpVHYgTXTd82KfUufa1nz
          Yt1VVoybiQei9q+rEhrvGZ69+QuxI96fb60ZM4XyiuXEids4U6Td2Xy+iqA=
          -----END RSA PRIVATE KEY-----
