version: '2.1'
services:
  sapphire:
    extends:
      file: config.yml
      service: sapphire
    build:
      context: ${SAPPHIRE_DIR}
      dockerfile: Dockerfile.dev
    image: myriadeinc/sapphire:dev
    command: ["bash", "-c", "npm install --dev && npm run migration:up && npm run start:dev"]
    volumes:
      - ${SAPPHIRE_DIR}:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8081:8081"
      - "9870:9870"
    depends_on:
      db:
          condition: service_healthy
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=myriade
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgres/data
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 1s
      timeout: 1s
      retries: 100