version: '2.1'
services:
  diamond:
    extends:
      file: config.yml
      service: sapphire
    build:
        context: ./
        dockerfile: Dockerfile.dev
    image: myriade/sapphire:dev
    command: ["bash", "-c", "npm run migration:up && npm run start:dev"]
    environment:
      - NODE_ENV=local
    volumes:
      - ./:/usr/src/app
    ports:
      - "8081:8081"
      - "9873:9873"
    depends_on:
      db:
        condition: service_healthy
